### PR TITLE
Send Receive updates

### LINKED ISSUE #31: Determine whether to use window.InnerHeight or 100vh in Send page component
We merged `max-send` branch to get that functionality into `develop`, however @dmihal had changed:

`height: ${window.innerHeight};` to `height: 100vh;` within the `Modal Backdrop` const. 

@carlfairclough Do you want to revert to `window.innerHeight`? If so, @dmihal proposed that we would need to add `px` to the end i.e. `height: ${window.innerHeight}px;`

We'll let you decide.

### LINKED ISSUE #43: Does not stop accessing camera after opening & closing QR scanner
In chrome, open the QR scanner.
After closing the QR scanner, the website will still be accessing the camera

Is the component unmounting?

### PR DESCRIPTION
**Pull request by carlfairclough**
This brings in the changes from #37 in a non-breaking way. It's still a large PR but includes little rearchitecting. @dmihal, I'm not sure how the QR scanner handles requests, but I'm using URL params to match things. I can't test scanning right now.

It also resolves #31 as it is only used in one place, and resolves #43

Please review & test

### Notes
 - Scanning logic is not changed
 - Updated send/receive screens are in there
 - Updated QR *styling* is in, only.

### CODE REVIEW

**Comment by as-dr** [comment]
We should replace the `CurrencyInput` with the original `RimbleAmountInput` so that we don't re-introduce the injut hijack bug.

I tested this and everything is working. Don't want to comment on the code implementation, I'd prefer to let @dmihal make that call.

**Comment by as-dr** [comment]
Unfortunately, we've run out of time and it's just too risky to try and get this integrated mere hours before we ship.

Lessons & advice for next time:

1. Create smaller PRs that focus on updating smaller elements of functionality.
1. Keep in sync with the team so they know what work is being done and where.
1. Prioritize merging of elements like this that can cause a bottleneck in front of other work.

**Comment by carlfairclough** [comment]
Kindly disagree @as-dr.

Nothing amazing happening other than a modal layer which listens for send + receive URLs and is functional. This is only a major change in how it listens to the URL from a different place: `Modals.tsx` instead of `Pages.tsx`.

It's impossible to chunk something like that as it's a network of interconnected parts i.e. I won't open a PR just for the modals as pages as it doesn't work without hamfisted psuedo-routing.

**Comment by as-dr** [comment]
@carlfairclough I wanted nothing more than to get this in. It makes complete sense. But it's Friday and it's still not in, so we have to pull the plug. 

This was a management / organisational and time issue and if it wasn't possible to chunk this into smaller PRs then the full scope of this should have been discussed prior to embarking on the work so we could prioritize getting it completed and merged in.

I am just as disappointed as you are.

**Pull request closed without merging**
