### PR TITLE
Add asset icons (WIP)

### PR DESCRIPTION
**Pull request by as-dr**
This adds icons for ETH, Dai & Xdai and updates the `BalanceItem` element to accommodate them.

**I couldn't figure out how to conditionally display the correct asset icon for the correct asset** so I need help on that implementation, please :v:

### CODE REVIEW

**Comment by as-dr** [comment]
@dmihal Since Carl is traveling can I make you the primary on this, please?

**Comment by carlfairclough** [comment]
This is functional, and covers xDai, Dai, gEth (as Eth)

**Review by carlfairclough — APPROVED** [review]

**Review by as-dr — COMMENTED** [review]
Tested with kETH and it works. Please merge when you have a moment @dmihal

**Comment by dmihal** [comment]
Re-opening after revert

**Pull request merged**
